# Dockerfile.dev
FROM python:3.12-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl build-essential && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Dev tools
RUN pip install uvicorn fastapi[all] watchdog

COPY . .

EXPOSE 8000
COPY setup.sh setup.sh
CMD ["bash", "./setup.sh", "--dev"]
